import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import Link from "next/link";

import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Bonzai Proxy Chat",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased px-2 md:px-4`}
      >
      <header className="bg-sidebar text-sidebar-foreground border-sidebar-border border border-t-0 px-4 py-2 rounded-b-lg">
          <div className="flex grow gap-2">
              <Link href="/" className="font-bold">Bonzai Chat</Link>
              <Link href="/about" className="font-light">About</Link>
          </div>
      </header>
        {children}
      </body>
    </html>
  );
}
